### ISSUE TITLE
Error while deploying to Heroku

### ISSUE THREAD

**Issue by DominikGuzei** [francocatena/meteor-compass#3]
Hey there,
I have scss and your package correctly set up and it works locally during development.
When I try to push it to heroku (deploy) then it always fails due to the missing import for compass.

I saw that you described this problem in the readme, but do you have any idea how I can prevent this error from happening while heroku builds my app?

**Comment by francocatena** [comment]
Hi @DominikGuzei 

I don't use Heroku, but is probably related to the _first run bug_. I'll make some test on Heroku during this weekend and come back to you with some feedback.

When you deploy to meteor.com or using MUP, you build on your own machine and generate the CSS there, so this never happen.

Cheers.

**Comment by francocatena** [comment]
Hi @DominikGuzei,

Such a long time, but this should be fixed now, thanks to the new Meteor build system (only on Meteor 1.2).

If you are still using this, give it a try and let me know of any issues.

Cheers.
