### ISSUE TITLE
Importing the Clearfix mixin

### ISSUE THREAD

**Issue by happy-dev** [francocatena/meteor-compass#7]
Hi Franco,

Many thanks for your plugin!
I am trying to import compass' [Clearfix](http://compass-style.org/reference/compass/utilities/general/clearfix/) mixin, but I don't manage to. This is hiw I am doing it : 
1. I installed this module
2. I wrote a **scss.json file** at the root of my project, containing the following :
```javascript
{
  "includePaths": [
    ".meteor/local/build/programs/server/assets/packages/francocatena_compass"
  ]
}
```
3. I tried both **@import "compass/utilities/general/clearfix";** and **@import "compass/clearfix";** at the beginning of my scss file
4. I get the following error in the console : 
```
While building the application:
   /root/html/lybe/client/style/settings/_mixins.scss:1:9: Scss compiler error: file to import not found
   or unreadable: compass/clearfix
   Current dir: /root/html/lybe/client/style/settings/
```

I am not sure what to do. Any suggestion? 
Many thanks for your time and efforts

**Comment by dapids** [comment]
Same error here. It showed up after updating to the version 1.2.

**Comment by francocatena** [comment]
Hi @happy-dev / @dapids,

Meteor 1.2 introduces some new methods on the package side (like Package.registerBuildPlugin) that will help a lot on making this a cleaner package (I hope the bug that blows the first start will be gone with it).

Unfortunatelly it appears to brake the current form of it. Let me check what I can do, and I'll come back with a new version compatible with it (and probably updating the compass version as well, since progress has been made on the libsass world).

Cheers.

**Comment by happy-dev** [comment]
+1

Let us know if we can help in some way

2015-09-26 22:44 GMT+02:00 Franco Catena <notifications@github.com>:

> Hi @happy-dev <https://github.com/happy-dev> / @dapids
> <https://github.com/dapids>,
>
> Meteor 1.2 introduces some new methods on the package side (like
> Package.registerBuildPlugin) that will help a lot on making this a cleaner
> package (I hope the bug that blows the first start will be gone with it).
>
> Unfortunatelly it appears to brake the current form of it. Let me check
> what I can do, and I'll come back with a new version compatible with it
> (and probably updating the compass version as well, since progress has been
> made on the libsass world).
>
> Cheers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/francocatena/meteor-compass/issues/7#issuecomment-143493530>
> .
>



-- 
Alexandre BOURLIER
06 51 71 08 21
http://happy-dev.fr

PS : pour les urgences, je suis réactif par téléphone

**Comment by francocatena** [comment]
Well, we have a 1.2 compatible version =)

Be aware of the new syntax:

``` scss
@import "{francocatena:compass}/compass/utilities/general/clearfix";
```

Try it and let me know any issues.

Cheers.

**Comment by francocatena** [comment]
Forgot to mention, we don't need the scss.json file anymore.

**Comment by YannDanthu** [comment]
Hi,
is this the version 0.6.0 ?

cheers

**Comment by francocatena** [comment]
Hi @YannDanthu,

Yes, version 0.6.0 adds Meteor 1.2 support.

Cheers.

**Comment by YannDanthu** [comment]
Ok great.
Then I have a different issue, no mixing named display-flex

But this may not be related to meteor-compass.

Cheers.

**Comment by happy-dev** [comment]
Thanks for taking the time.

I am about to start a new Meteor project.
I'll reach back once I have tried this.

All the best!

2015-10-13 17:23 GMT+02:00 Franco Catena notifications@github.com:

> Well, we have a 1.2 compatible version =)
> 
> Be aware of the new syntax:
> 
> @import "{francocatena:compass}/compass/utilities/general/clearfix";
> 
> Try it and let me know any issues.
> 
> Cheers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/francocatena/meteor-compass/issues/7#issuecomment-147749139
> .

## 

Alexandre BOURLIER
06 51 71 08 21
http://happy-dev.fr

PS : pour les urgences, je suis réactif par téléphone
