### ISSUE TITLE
unable to load compass

### ISSUE THREAD

**Issue by wykhuh** [francocatena/meteor-compass#8]
I upgrade Meteor 1.2.0.2. When I start Meteor, I get an error. I stopped and restarted the app as per the README, but that did not solve the problem.

 `While processing files with fourseven:scss (for target web.browser):
   /main.scss: Scss compiler error: File to import: compass not found. Import origin: /main.scss`

**Comment by francocatena** [comment]
Hi @wykhuh,

Now this package is compatible with Meteor 1.2.

Be aware of the new syntax:

``` scss
@import "{francocatena:compass}/compass";
```

Try it and let me know any issues.

Cheers.
